### PR TITLE
Initial java client

### PR DESCRIPTION
**Pull request by georgevanburgh**
Added a basic Java client, and some documentation on getting started. Not the cleanest implementation in the world - but should be sufficient.

### CODE REVIEW

**Comment by nadvamir** [comment]
I already did a Java client in PR29 (unmerged). Now we need to Java-off :D

**Comment by georgevanburgh** [comment]
Oops 😂 Serves me right for not checking first 😛 

I'm sure we could combine the two fairly easily - we both used the same REST client after all! I much prefer your choice of gradle over maven, though. If there's nothing useful in this PR, I'm happy to close it out in deference of #29

**Comment by JamesWP** [comment]
I'll say that although this is more idiomatic java, with nice types for everything. #29 looks more similar to the other examples we have. I can't comment on the repository part. no preference there

**Review by JamesWP — APPROVED** [review]

**Comment by nadvamir** [comment]
This is a more idiomatic Java than whatever I did (apart from C# naming conventions :P). I'll keep #29 because it is marginally simpler as an example and it is more similar to the rest. Also, the API is a bit clearer there, you chose `String.format` instead of `Unirest.routeParam` for creating the URLs and while that makes code shorter, this becomes harder to follow as an example.

**Pull request closed without merging**
